version: '3.4'

volumes:
    postgres:

services:
  webapplication1:
    container_name: webapplication1
    image: ${DOCKER_REGISTRY-}webapplication1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports: 
      - "5000:80"
  
  postgres: 
    container_name: postgresmimicdb
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgadmin
      PGDATA: /data/postgres
      POSTGRES_DB: Mimicdb
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: always
